server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: codelensx-backend
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  
  datasource:
    url: jdbc:postgresql://localhost:5432/codelensx
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  jwt:
    # 512-bit HS512 secret key base64 encoded
    secret: dGhpcy1pcy1hLXZlcnktc2VjdXJlLWFuZC1sb25nLXNlY3JldC1rZXktZm9yLWNvZGVsZW5zeC1qd3QtYXV0aGVudGljYXRpb24tc2VjdXJpdHkK
    expiration-ms: 86400000 # 24 Hours
  gemini:
    api-key: ${GEMINI_API_KEY:}
    model: gemini-1.5-flash
    temperature: 0.2

